import type { Conversation, ConversationSearchResults } from "./types";

export const conversationsMockData: Conversation[] = [
	{
		id: "1",
		agent: {
			id: "agent1",
			name: "John Smith",
			email: "john.smith@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "1",
			content: "Hello, I hope you're having a great day! I wanted to discuss the recent customer refund issue that came up. The customer has provided all the necessary documentation and transaction details. I've reviewed the case thoroughly and believe we should process the refund according to our standard 30-day policy. Could you please take a look and provide your guidance on how to proceed with this situation?",
			createdAt: "2025-05-15T09:30:00Z",
			sender: {
				id: "agent1",
				name: "John Smith",
				email: "john.smith@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "1",
		},
		createdAt: "2024-01-15T09:30:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl1",
				name: "Sarah Johnson",
				email: "sarah.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl2",
				name: "Mike Chen",
				email: "mike.c@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Customer Refund Issue",
		unreadMessagesCount: 0,
	},
	{
		id: "2",
		agent: {
			id: "agent2",
			name: "Emily Davis",
			email: "emily.davis@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "2",
			content: "Need assistance with technical issues",
			createdAt: "2025-05-14T10:15:00Z",
			sender: {
				id: "agent2",
				name: "Emily Davis",
				email: "emily.davis@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "2",
		},
		createdAt: "2025-05-17T10:15:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl3",
				name: "David Wilson",
				email: "david.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Technical Support Escalation",
		unreadMessagesCount: 0,
	},
	{
		id: "3",
		agent: {
			id: "agent3",
			name: "Michael Brown",
			email: "michael.brown@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "3",
			content: "Feature request submitted for review",
			createdAt: "2024-01-15T11:00:00Z",
			sender: {
				id: "agent3",
				name: "Michael Brown",
				email: "michael.brown@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "3",
		},
		createdAt: "2024-01-15T11:00:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl4",
				name: "Lisa Anderson",
				email: "lisa.a@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl5",
				name: "James Taylor",
				email: "james.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl6",
				name: "Maria Garcia",
				email: "maria.g@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl7",
				name: "Robert Kim",
				email: "robert.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl8",
				name: "John Doe",
				email: "john.doe@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl9",
				name: "Jane Smith",
				email: "jane.smith@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl10",
				name: "John Doe",
				email: "john.doe@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl11",
				name: "Jane Smith",
				email: "jane.smith@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},

			{
				id: "tl12",
				name: "John Doe",
				email: "john.doe@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl13",
				name: "Jane Smith",
				email: "jane.smith@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},

			{
				id: "tl14",
				name: "John Doe",
				email: "john.doe@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},




		],
		topic: "Product Feature Request",
		unreadMessagesCount: 0,
	},
	{
		id: "4",
		agent: {
			id: "agent4",
			name: "Jessica Lee",
			email: "jessica.lee@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "4",
			content: "Billing dispute needs immediate attention",
			createdAt: "2024-01-15T11:45:00Z",
			sender: {
				id: "agent4",
				name: "Jessica Lee",
				email: "jessica.lee@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "4",
		},
		createdAt: "2024-01-15T11:45:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl7",
				name: "Robert Kim",
				email: "robert.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl1",
				name: "Sarah Johnson",
				email: "sarah.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Billing Dispute",
		unreadMessagesCount: 3,
	},
	{
		id: "5",
		agent: {
			id: "agent5",
			name: "Alex Turner",
			email: "alex.turner@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "5",
			content: "Service outage reported in region A",
			createdAt: "2024-01-15T12:30:00Z",
			sender: {
				id: "agent5",
				name: "Alex Turner",
				email: "alex.turner@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "5",
		},
		createdAt: "2024-01-15T12:30:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl3",
				name: "David Wilson",
				email: "david.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl5",
				name: "James Taylor",
				email: "james.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl7",
				name: "Robert Kim",
				email: "robert.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Service Outage Report",
		unreadMessagesCount: 0,
	},
	{
		id: "6",
		agent: {
			id: "agent6",
			name: "Emily Chen",
			email: "emily.chen@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "6",
			content: "Account access issue resolved",
			createdAt: "2024-01-15T13:15:00Z",
			sender: {
				id: "agent6",
				name: "Emily Chen",
				email: "emily.chen@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "6",
		},
		createdAt: "2024-01-15T13:15:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl2",
				name: "Michael Brown",
				email: "michael.b@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Account Access Issues",
		unreadMessagesCount: 0,
	},
	{
		id: "7",
		agent: {
			id: "agent7",
			name: "Sofia Rodriguez",
			email: "sofia.r@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "7",
			content: "New feature request submitted",
			createdAt: "2024-01-15T14:00:00Z",
			sender: {
				id: "agent7",
				name: "Sofia Rodriguez",
				email: "sofia.r@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "7",
		},
		createdAt: "2024-01-15T14:00:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl4",
				name: "Emma Davis",
				email: "emma.d@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl6",
				name: "Lisa Wang",
				email: "lisa.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Feature Request",
		unreadMessagesCount: 4,
	},
	{
		id: "8",
		agent: {
			id: "agent8",
			name: "Marcus Johnson",
			email: "marcus.j@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "8",
			content: "Performance issues detected in module B",
			createdAt: "2024-01-15T14:45:00Z",
			sender: {
				id: "agent8",
				name: "Marcus Johnson",
				email: "marcus.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "8",
		},
		createdAt: "2024-01-15T14:45:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl1",
				name: "Sarah Johnson",
				email: "sarah.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl3",
				name: "David Wilson",
				email: "david.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Performance Issues",
		unreadMessagesCount: 0,
	},
	{
		id: "9",
		agent: {
			id: "agent9",
			name: "Rachel Green",
			email: "rachel.g@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "9",
			content: "Data migration completed successfully",
			createdAt: "2024-01-15T15:30:00Z",
			sender: {
				id: "agent9",
				name: "Rachel Green",
				email: "rachel.g@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "9",
		},
		createdAt: "2024-01-15T15:30:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl5",
				name: "James Taylor",
				email: "james.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Data Migration Support",
		unreadMessagesCount: 0,
	},
	{
		id: "10",
		agent: {
			id: "agent10",
			name: "Daniel Lee",
			email: "daniel.l@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "10",
			content: "Integration setup in progress",
			createdAt: "2024-01-15T16:15:00Z",
			sender: {
				id: "agent10",
				name: "Daniel Lee",
				email: "daniel.l@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "10",
		},
		createdAt: "2024-01-15T16:15:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl2",
				name: "Michael Brown",
				email: "michael.b@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl7",
				name: "Robert Kim",
				email: "robert.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Integration Setup",
		unreadMessagesCount: 2,
	},
	{
		id: "11",
		agent: {
			id: "agent11",
			name: "Jessica Martinez",
			email: "jessica.m@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "11",
			content: "Security concerns need immediate review",
			createdAt: "2024-01-15T17:00:00Z",
			sender: {
				id: "agent11",
				name: "Jessica Martinez",
				email: "jessica.m@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "11",
		},
		createdAt: "2024-01-15T17:00:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl4",
				name: "Emma Davis",
				email: "emma.d@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Security Concerns",
		unreadMessagesCount: 0,
	},
	{
		id: "12",
		agent: {
			id: "agent12",
			name: "Thomas Anderson",
			email: "thomas.a@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "12",
			content: "API documentation updated",
			createdAt: "2024-01-15T17:45:00Z",
			sender: {
				id: "agent12",
				name: "Thomas Anderson",
				email: "thomas.a@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "12",
		},
		createdAt: "2024-01-15T17:45:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl6",
				name: "Lisa Wang",
				email: "lisa.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl1",
				name: "Sarah Johnson",
				email: "sarah.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "API Documentation",
		unreadMessagesCount: 0,
	},
	{
		id: "13",
		agent: {
			id: "agent13",
			name: "Laura Thompson",
			email: "laura.t@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "13",
			content: "User training session scheduled",
			createdAt: "2024-01-15T18:30:00Z",
			sender: {
				id: "agent13",
				name: "Laura Thompson",
				email: "laura.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "13",
		},
		createdAt: "2024-01-15T18:30:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl3",
				name: "David Wilson",
				email: "david.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "User Training Request",
		unreadMessagesCount: 1,
	},
	{
		id: "14",
		agent: {
			id: "agent14",
			name: "Kevin Park",
			email: "kevin.p@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "14",
			content: "Database optimization required",
			createdAt: "2024-01-15T19:15:00Z",
			sender: {
				id: "agent14",
				name: "Kevin Park",
				email: "kevin.p@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "14",
		},
		createdAt: "2024-01-15T19:15:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl5",
				name: "James Taylor",
				email: "james.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl7",
				name: "Robert Kim",
				email: "robert.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Database Optimization",
		unreadMessagesCount: 0,
	},
	{
		id: "15",
		agent: {
			id: "agent15",
			name: "Anna White",
			email: "anna.w@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "15",
			content: "Deployment issues resolved",
			createdAt: "2024-01-15T20:00:00Z",
			sender: {
				id: "agent15",
				name: "Anna White",
				email: "anna.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "15",
		},
		createdAt: "2024-01-15T20:00:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl2",
				name: "Michael Brown",
				email: "michael.b@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Deployment Issues",
		unreadMessagesCount: 0,
	},
	{
		id: "16",
		agent: {
			id: "agent16",
			name: "Chris Morgan",
			email: "chris.m@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "16",
			content: "Custom integration requirements gathered",
			createdAt: "2024-01-12T20:45:00Z",
			sender: {
				id: "agent16",
				name: "Chris Morgan",
				email: "chris.m@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "16",
		},
		createdAt: "2024-01-14T20:45:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl4",
				name: "Emma Davis",
				email: "emma.d@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl6",
				name: "Lisa Wang",
				email: "lisa.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Custom Integration",
		unreadMessagesCount: 5,
	},
	{
		id: "17",
		agent: {
			id: "agent17",
			name: "Michelle Zhang",
			email: "michelle.z@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "17",
			content: "Performance monitoring setup needed",
			createdAt: "2024-01-15T21:30:00Z",
			sender: {
				id: "agent17",
				name: "Michelle Zhang",
				email: "michelle.z@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "17",
		},
		createdAt: "2024-01-15T21:30:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl1",
				name: "Sarah Johnson",
				email: "sarah.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Performance Monitoring",
		unreadMessagesCount: 0,
	},
	{
		id: "18",
		agent: {
			id: "agent18",
			name: "Ryan Cooper",
			email: "ryan.c@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "18",
			content: "Data analysis request completed",
			createdAt: "2024-01-15T22:15:00Z",
			sender: {
				id: "agent18",
				name: "Ryan Cooper",
				email: "ryan.c@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "18",
		},
		createdAt: "2024-01-15T22:15:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl3",
				name: "David Wilson",
				email: "david.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl5",
				name: "James Taylor",
				email: "james.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Data Analysis Request",
		unreadMessagesCount: 0,
	},
	{
		id: "19",
		agent: {
			id: "agent19",
			name: "Sandra Miller",
			email: "sandra.m@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "19",
			content: "User authentication issues reported",
			createdAt: "2024-01-15T23:00:00Z",
			sender: {
				id: "agent19",
				name: "Sandra Miller",
				email: "sandra.m@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "19",
		},
		createdAt: "2024-01-15T23:00:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl7",
				name: "Robert Kim",
				email: "robert.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "User Authentication",
		unreadMessagesCount: 1,
	},
	{
		id: "20",
		agent: {
			id: "agent20",
			name: "Brian Wilson",
			email: "brian.w@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "20",
			content: "Cloud infrastructure review requested",
			createdAt: "2024-01-15T23:45:00Z",
			sender: {
				id: "agent20",
				name: "Brian Wilson",
				email: "brian.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "20",
		},
		createdAt: "2024-01-15T23:45:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl2",
				name: "Michael Brown",
				email: "michael.b@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl4",
				name: "Emma Davis",
				email: "emma.d@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Cloud Infrastructure",
		unreadMessagesCount: 0,
	},
	{
		id: "21",
		agent: {
			id: "agent21",
			name: "Diana Clark",
			email: "diana.c@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "21",
			content: "Mobile app crash report analysis",
			createdAt: "2024-01-16T00:30:00Z",
			sender: {
				id: "agent21",
				name: "Diana Clark",
				email: "diana.c@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "21",
		},
		createdAt: "2024-01-16T00:30:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl6",
				name: "Lisa Wang",
				email: "lisa.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Mobile App Support",
		unreadMessagesCount: 0,
	},
	{
		id: "22",
		agent: {
			id: "agent22",
			name: "Peter Chang",
			email: "peter.c@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "22",
			content: "System architecture review meeting notes",
			createdAt: "2024-01-16T01:15:00Z",
			sender: {
				id: "agent22",
				name: "Peter Chang",
				email: "peter.c@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "22",
		},
		createdAt: "2024-01-16T01:15:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl1",
				name: "Sarah Johnson",
				email: "sarah.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl3",
				name: "David Wilson",
				email: "david.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "System Architecture",
		unreadMessagesCount: 1,
	},
	{
		id: "23",
		agent: {
			id: "agent23",
			name: "Maria Garcia",
			email: "maria.g@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "23",
			content: "Data migration timeline proposal",
			createdAt: "2024-01-16T02:00:00Z",
			sender: {
				id: "agent23",
				name: "Maria Garcia",
				email: "maria.g@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "23",
		},
		createdAt: "2024-01-16T02:00:00Z",
		status: "pending" as const,
		teamLeaders: [
			{
				id: "tl5",
				name: "James Taylor",
				email: "james.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Data Migration Plan",
		unreadMessagesCount: 0,
	},
	{
		id: "24",
		agent: {
			id: "agent24",
			name: "John Baker",
			email: "john.b@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "24",
			content: "Security audit findings report",
			createdAt: "2024-01-16T02:45:00Z",
			sender: {
				id: "agent24",
				name: "John Baker",
				email: "john.b@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: true,
			conversationId: "24",
		},
		createdAt: "2024-01-16T02:45:00Z",
		status: "closed" as const,
		teamLeaders: [
			{
				id: "tl7",
				name: "Robert Kim",
				email: "robert.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			},
			{
				id: "tl2",
				name: "Michael Brown",
				email: "michael.b@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "Security Audit",
		unreadMessagesCount: 0,
	},
	{
		id: "25",
		agent: {
			id: "agent25",
			name: "Amanda Foster",
			email: "amanda.f@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		lastMessage: {
			id: "25",
			content: "API integration status update",
			createdAt: "2024-01-16T03:30:00Z",
			sender: {
				id: "agent25",
				name: "Amanda Foster",
				email: "amanda.f@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			isRead: false,
			conversationId: "25",
		},
		createdAt: "2024-01-16T03:30:00Z",
		status: "active" as const,
		teamLeaders: [
			{
				id: "tl4",
				name: "Emma Davis",
				email: "emma.d@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "team_lead" as const,
			}
		],
		topic: "API Integration",
		unreadMessagesCount: 1,
	}


];


export const conversationSearchResults: ConversationSearchResults[] = [
	{
		id: "1",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T10:00:00Z",
		message: {
			id: "1",
			content: "Hi there! I'm reaching out because I noticed some unusual activity on our payment processing system Could you help me investigate this? I've already checked the logs and found a few anomalies that I'd like to discuss with you. The transactions in question occurred between 2:00 PM and 4:00 PM yesterday.",
			createdAt: "2025-05-17T10:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "1",
		},
	},
	{
		id: "2",
		agent: {
			id: "agent2",
			name: "Emily Davis",
			email: "emily.davis@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T10:15:00Z",
		message: {
			id: "msg2",
			content: "Need assistance with customer refund policy interpretation",
			createdAt: "2024-01-15T10:15:00Z",
			sender: {
				id: "agent2",
				name: "Emily Davis",
				email: "emily.davis@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "2",
		},
	},
	{
		id: "3",
		agent: {
			id: "agent3",
			name: "Michael Wong",
			email: "michael.w@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T11:00:00Z",
		message: {
			id: "msg3",
			content: "Escalating this case due to security concerns",
			createdAt: "2024-01-15T11:00:00Z",
			sender: {
				id: "agent3",
				name: "Michael Wong",
				email: "michael.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "3",
		},
	},
	{
		id: "4",
		agent: {
			id: "agent4",
			name: "Sarah Johnson",
			email: "sarah.j@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T11:30:00Z",
		message: {
			id: "msg4",
			content: "Customer requesting expedited shipping options",
			createdAt: "2024-01-15T11:30:00Z",
			sender: {
				id: "agent4",
				name: "Sarah Johnson",
				email: "sarah.j@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "4",
		},
	},
	{
		id: "5",
		agent: {
			id: "agent5",
			name: "David Wilson",
			email: "david.w@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T12:00:00Z",
		message: {
			id: "msg5",
			content: "Technical issue with payment gateway integration",
			createdAt: "2024-01-15T12:00:00Z",
			sender: {
				id: "agent5",
				name: "David Wilson",
				email: "david.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "5",
		},
	},
	{
		id: "6",
		agent: {
			id: "agent6",
			name: "Lisa Chen",
			email: "lisa.c@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T13:00:00Z",
		message: {
			id: "msg6",
			content: "Following up on previous escalation regarding account access",
			createdAt: "2024-01-15T13:00:00Z",
			sender: {
				id: "agent6",
				name: "Lisa Chen",
				email: "lisa.c@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "6",
		},
	},
	{
		id: "7",
		agent: {
			id: "agent7",
			name: "Robert Taylor",
			email: "robert.t@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T14:00:00Z",
		message: {
			id: "msg7",
			content: "Resolved billing dispute for order #78234",
			createdAt: "2024-01-15T14:00:00Z",
			sender: {
				id: "agent7",
				name: "Robert Taylor",
				email: "robert.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "7",
		},
	},
	{
		id: "8",
		agent: {
			id: "agent8",
			name: "Amanda Lee",
			email: "amanda.l@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T15:00:00Z",
		message: {
			id: "msg8",
			content: "Customer inquiring about bulk order discounts",
			createdAt: "2024-01-15T15:00:00Z",
			sender: {
				id: "agent8",
				name: "Amanda Lee",
				email: "amanda.l@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "8",
		},
	},
	{
		id: "9",
		agent: {
			id: "agent9",
			name: "Kevin Martinez",
			email: "kevin.m@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T16:00:00Z",
		message: {
			id: "msg9",
			content: "Need assistance with international shipping regulations",
			createdAt: "2024-01-15T16:00:00Z",
			sender: {
				id: "agent9",
				name: "Kevin Martinez",
				email: "kevin.m@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "9",
		},
	},
	{
		id: "10",
		agent: {
			id: "agent10",
			name: "Rachel Kim",
			email: "rachel.k@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T17:00:00Z",
		message: {
			id: "msg10",
			content: "Customer requesting product customization options",
			createdAt: "2024-01-15T17:00:00Z",
			sender: {
				id: "agent10",
				name: "Rachel Kim",
				email: "rachel.k@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "10",
		},
	},
	{
		id: "11",
		agent: {
			id: "agent11",
			name: "Thomas Anderson",
			email: "thomas.a@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T18:00:00Z",
		message: {
			id: "msg11",
			content: "Completed security verification process",
			createdAt: "2024-01-15T18:00:00Z",
			sender: {
				id: "agent11",
				name: "Thomas Anderson",
				email: "thomas.a@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "11",
		},
	},
	{
		id: "12",
		agent: {
			id: "agent12",
			name: "Jessica Brown",
			email: "jessica.b@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T19:00:00Z",
		message: {
			id: "msg12",
			content: "Discussing warranty extension options with customer",
			createdAt: "2024-01-15T19:00:00Z",
			sender: {
				id: "agent12",
				name: "Jessica Brown",
				email: "jessica.b@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "12",
		},
	},
	{
		id: "13",
		agent: {
			id: "agent13",
			name: "Daniel Park",
			email: "daniel.p@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T20:00:00Z",
		message: {
			id: "msg13",
			content: "Investigating reported platform performance issues",
			createdAt: "2024-01-15T20:00:00Z",
			sender: {
				id: "agent13",
				name: "Daniel Park",
				email: "daniel.p@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "13",
		},
	},
	{
		id: "14",
		agent: {
			id: "agent14",
			name: "Michelle Garcia",
			email: "michelle.g@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T21:00:00Z",
		message: {
			id: "msg14",
			content: "Processing bulk order request for corporate client",
			createdAt: "2024-01-15T21:00:00Z",
			sender: {
				id: "agent14",
				name: "Michelle Garcia",
				email: "michelle.g@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "14",
		},
	},
	{
		id: "15",
		agent: {
			id: "agent15",
			name: "Christopher Lee",
			email: "chris.l@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T22:00:00Z",
		message: {
			id: "msg15",
			content: "Resolved API integration issues for client",
			createdAt: "2024-01-15T22:00:00Z",
			sender: {
				id: "agent15",
				name: "Christopher Lee",
				email: "chris.l@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "15",
		},
	},
	{
		id: "16",
		agent: {
			id: "agent16",
			name: "Jennifer Wilson",
			email: "jennifer.w@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T23:00:00Z",
		message: {
			id: "msg16",
			content: "Addressing customer feedback on new feature release",
			createdAt: "2024-01-15T23:00:00Z",
			sender: {
				id: "agent16",
				name: "Jennifer Wilson",
				email: "jennifer.w@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "16",
		},
	},
	{
		id: "17",
		agent: {
			id: "agent17",
			name: "Brian Taylor",
			email: "brian.t@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-16T00:00:00Z",
		message: {
			id: "msg17",
			content: "Reviewing security compliance requirements",
			createdAt: "2024-01-16T00:00:00Z",
			sender: {
				id: "agent17",
				name: "Brian Taylor",
				email: "brian.t@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "17",
		},
	},
	{
		id: "18",
		agent: {
			id: "agent18",
			name: "Nicole Martinez",
			email: "nicole.m@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-16T01:00:00Z",
		message: {
			id: "msg18",
			content: "Coordinating deployment schedule with client",
			createdAt: "2024-01-16T01:00:00Z",
			sender: {
				id: "agent18",
				name: "Nicole Martinez",
				email: "nicole.m@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "18",
		},
	},
	{
		id: "19",
		agent: {
			id: "agent19",
			name: "Steven Chang",
			email: "steven.c@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-16T02:00:00Z",
		message: {
			id: "msg19",
			content: "Completed annual security audit review",
			createdAt: "2024-01-16T02:00:00Z",
			sender: {
				id: "agent19",
				name: "Steven Chang",
				email: "steven.c@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "19",
		},
	},
	{
		id: "20",
		agent: {
			id: "agent20",
			name: "Laura Rodriguez",
			email: "laura.r@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-16T03:00:00Z",
		message: {
			id: "msg20",
			content: "Discussing service level agreement terms",
			createdAt: "2024-01-16T03:00:00Z",
			sender: {
				id: "agent20",
				name: "Laura Rodriguez",
				email: "laura.r@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "20",
		},
	},
	{
		id: "21",
		agent: {
			id: "agent21",
			name: "William Foster",
			email: "william.f@teamtalk.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-16T04:00:00Z",
		message: {
			id: "msg21",
			content: "Evaluating new feature request from enterprise client",
			createdAt: "2024-01-16T04:00:00Z",
			sender: {
				id: "agent21",
				name: "William Foster",
				email: "william.f@teamtalk.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "21",
		},
	},
];


export const myConversations: Omit<Conversation, "teamLeaders" | "topic">[] = [
	{
		id: "1",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T16:00:00Z",
		lastMessage: {
			id: "msg1",
			content: "Hello, how are you?",
			createdAt: "2024-01-15T16:00:00Z",
			sender: {
				id: "0kssnJ3G0stVdH7CABCJFA7GUB4xP3l7",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "1",
			isRead: false,
		},
		status: "active",
	},
	{
		id: "2",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T17:00:00Z",
		lastMessage: {
			id: "msg2",
			content: "Need help with account settings",
			createdAt: "2024-01-15T17:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "2",
			isRead: true,
		},
		status: "active",
	},
	{
		id: "3",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T18:00:00Z",
		lastMessage: {
			id: "msg3",
			content: "Discussing billing issues",
			createdAt: "2024-01-15T18:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "3",
			isRead: false,
		},
		status: "active",
	},
	{
		id: "4",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T19:00:00Z",
		lastMessage: {
			id: "msg4",
			content: "Technical support needed",
			createdAt: "2024-01-15T19:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "4",
			isRead: true,
		},
		status: "active",
	},
	{
		id: "5",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-15T20:00:00Z",
		lastMessage: {
			id: "msg5",
			content: "Product inquiry discussion",
			createdAt: "2024-01-15T20:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "5",
			isRead: false,
		},
		status: "active",
	},
	{
		id: "6",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-14T16:00:00Z",
		lastMessage: {
			id: "msg6",
			content: "Issue resolved successfully",
			createdAt: "2024-01-14T16:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "6",
			isRead: true,
		},
		status: "closed",
	},
	{
		id: "7",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-14T17:00:00Z",
		lastMessage: {
			id: "msg7",
			content: "Refund processed",
			createdAt: "2024-01-14T17:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "7",
			isRead: true,
		},
		status: "closed",
	},
	{
		id: "8",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-14T18:00:00Z",
		lastMessage: {
			id: "msg8",
			content: "Account settings updated",
			createdAt: "2024-01-14T18:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "8",
			isRead: true,
		},
		status: "closed",
	},
	{
		id: "9",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-14T19:00:00Z",
		lastMessage: {
			id: "msg9",
			content: "Technical issue fixed",
			createdAt: "2024-01-14T19:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "9",
			isRead: true,
		},
		status: "closed",
	},
	{
		id: "10",
		agent: {
			id: "agent1",
			name: "John Doe",
			email: "john.doe@example.com",
			image: "https://avatar.iran.liara.run/public",
			role: "csr" as const,
		},
		createdAt: "2024-01-14T20:00:00Z",
		lastMessage: {
			id: "msg10",
			content: "Order completed successfully",
			createdAt: "2024-01-14T20:00:00Z",
			sender: {
				id: "agent1",
				name: "John Doe",
				email: "john.doe@example.com",
				image: "https://avatar.iran.liara.run/public",
				role: "csr" as const,
			},
			conversationId: "10",
			isRead: true,
		},
		status: "closed",
	},


];

export const topics = [
	"Customer Refund Issue",
	"Technical Support Escalation",
	"System Architecture",
	"Data Migration Plan",
	"Security Audit",
	"API Integration",
]




